# Generated by Django 2.2.4 on 2019-09-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190911_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
