# Generated by Django 2.2.4 on 2019-09-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_shit'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvVaribles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneyratio_a', models.FloatField(default=1, null=True)),
                ('moneyratio_b', models.FloatField(default=1, null=True)),
                ('moneyratio_c', models.FloatField(default=1, null=True)),
                ('country_a_taxes', models.FloatField(default=1, null=True)),
                ('country_b_taxes', models.FloatField(default=1, null=True)),
                ('country_c_taxes', models.FloatField(default=1, null=True)),
                ('bidding_a1', models.IntegerField(default=1, null=True)),
                ('bidding_a2', models.IntegerField(default=1, null=True)),
                ('bidding_a3', models.IntegerField(default=1, null=True)),
                ('bidding_b1', models.IntegerField(default=1, null=True)),
                ('bidding_b2', models.IntegerField(default=1, null=True)),
                ('bidding_b3', models.IntegerField(default=1, null=True)),
                ('bidding_c1', models.IntegerField(default=1, null=True)),
                ('bidding_c2', models.IntegerField(default=1, null=True)),
                ('bidding_c3', models.IntegerField(default=1, null=True)),
            ],
        ),
    ]
