# Generated by Django 2.2.4 on 2019-09-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envvaribles',
            name='bidding_a1',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='envvaribles',
            name='bidding_a2',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='envvaribles',
            name='bidding_a3',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='envvaribles',
            name='bidding_b1',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='envvaribles',
            name='bidding_b2',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='envvaribles',
            name='bidding_b3',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='envvaribles',
            name='bidding_c1',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='envvaribles',
            name='bidding_c2',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='envvaribles',
            name='bidding_c3',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='活该',
            field=models.FloatField(default=1, null=True),
        ),
    ]
