# Generated by Django 2.2.4 on 2019-10-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postwithimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('upload_file', models.FileField(upload_to='post_files')),
            ],
        ),
    ]
