Factorylist = [
    {
        'takein':{            
                'a1':0,
                'a2':1,
                'a3':4,
        },
        'takeout':{
                'b1':0,
                'b2':2,
                'b3':1, 
        },
    },
    
]
#1 a 2b 3c
'''
FDICT = {
    1:{
        'f1':{
            'up0':{
                'intake':{
                    'a1':1,
                    'a2':0,
                    'a3':0,
                },
                'output':{
                    'b1':0,
                    'b2':0,
                    'b3':0,
                },
            },
            'up1':{
                'intake':{
                    'a1':2,
                    'a2':0,
                    'a3':0,
                },
                'output':{
                    'b1':0,
                    'b2':0,
                    'b3':0,
                },
            },
            'up2':{
                'intake':{
                    'a1':3,
                    'a2':0,
                    'a3':0,
                },
                'output':{
                    'b1':0,
                    'b2':0,
                    'b3':0,
                },
            },
            'up3':{
                'intake':{
                    'a1':4,
                    'a2':0,
                    'a3':0,
                },
                'output':{
                    'b1':0,
                    'b2':0,
                    'b3':0,
                },
            },
        },
        'f2':{
            'up0':{
                'intake':{
                    'a1':0,
                    'a2':0,
                    'a3':0,
                },
                'output':{
                    'b1':0,
                    'b2':0,
                    'b3':0,
                },
            },
            'up1':{
                'intake':{
                    'a1':0,
                    'a2':0,
                    'a3':0,
                },
                'output':{
                    'b1':0,
                    'b2':0,
                    'b3':0,
                },
            },
            'up2':{
                'intake':{
                    'a1':0,
                    'a2':0,
                    'a3':0,
                },
                'output':{
                    'b1':0,
                    'b2':0,
                    'b3':0,
                },
            },
            'up3':{
                'intake':{
                    'a1':0,
                    'a2':0,
                    'a3':0,
                },
                'output':{
                    'b1':0,
                    'b2':0,
                    'b3':0,
                },
            },
        },
        'f3':{
            'up0':{
                'intake':{
                    'a1':0,
                    'a2':0,
                    'a3':0,
                },
                'output':{
                    'b1':0,
                    'b2':0,
                    'b3':0,
                },
            },
            'up1':{
                'intake':{
                    'a1':0,
                    'a2':0,
                    'a3':0,
                },
                'output':{
                    'b1':0,
                    'b2':0,
                    'b3':0,
                },
            },
            'up2':{
                'intake':{
                    'a1':0,
                    'a2':0,
                    'a3':0,
                },
                'output':{
                    'b1':0,
                    'b2':0,
                    'b3':0,
                },
            },
            'up3':{
                'intake':{
                    'a1':0,
                    'a2':0,
                    'a3':0,
                },
                'output':{
                    'b1':0,
                    'b2':0,
                    'b3':0,
                },
            },
        },
    },
    2:{
        'f1':{
            'up0':{
                'intake':{
                    'b1':0,
                    'b2':0,
                    'b3':0,
                },
                'output':{
                    'c1':0,
                    'c2':0,
                    'c3':0,
                },
            },
            'up1':{
                'intake':{
                    'b1':0,
                    'b2':0,
                    'b3':0,
                },
                'output':{
                    'c1':0,
                    'c2':0,
                    'c3':0,
                },
            },
            'up2':{
                'intake':{
                    'b1':0,
                    'b2':0,
                    'b3':0,
                },
                'output':{
                    'c1':0,
                    'c2':0,
                    'c3':0,
                },
            },
            'up3':{
                'intake':{
                    'b1':0,
                    'b2':0,
                    'b3':0,
                },
                'output':{
                    'c1':0,
                    'c2':0,
                    'c3':0,
                },
            },
        },
        'f2':{
            'up0':{
                'intake':{
                    'b1':0,
                    'b2':0,
                    'b3':0,
                },
                'output':{
                    'c1':0,
                    'c2':0,
                    'c3':0,
                },
            },
            'up1':{
                'intake':{
                    'b1':0,
                    'b2':0,
                    'b3':0,
                },
                'output':{
                    'c1':0,
                    'c2':0,
                    'c3':0,
                },
            },
            'up2':{
                'intake':{
                    'b1':0,
                    'b2':0,
                    'b3':0,
                },
                'output':{
                    'c1':0,
                    'c2':0,
                    'c3':0,
                },
            },
            'up3':{
                'intake':{
                    'b1':0,
                    'b2':0,
                    'b3':0,
                },
                'output':{
                    'c1':0,
                    'c2':0,
                    'c3':0,
                },
            },
        },
        'f3':{
            'up0':{
                'intake':{
                    'b1':0,
                    'b2':0,
                    'b3':0,
                },
                'output':{
                    'c1':0,
                    'c2':0,
                    'c3':0,
                },
            },
            'up1':{
                'intake':{
                    'b1':0,
                    'b2':0,
                    'b3':0,
                },
                'output':{
                    'c1':0,
                    'c2':0,
                    'c3':0,
                },
            },
            'up2':{
                'intake':{
                    'b1':0,
                    'b2':0,
                    'b3':0,
                },
                'output':{
                    'c1':0,
                    'c2':0,
                    'c3':0,
                },
            },
            'up3':{
                'intake':{
                    'b1':0,
                    'b2':0,
                    'b3':0,
                },
                'output':{
                    'c1':0,
                    'c2':0,
                    'c3':0,
                },
            },
        },
    },
    3:{
        'f1':{
            'up0':{
                'intake':{
                    'c1':0,
                    'c2':0,
                    'c3':0,
                },
                'output':{
                    'a1':0,
                    'a2':0,
                    'a3':0,
                },
            },
            'up1':{
                'intake':{
                    'c1':0,
                    'c2':0,
                    'c3':0,
                },
                'output':{
                    'a1':0,
                    'a2':0,
                    'a3':0,
                },
            },
            'up2':{
                'intake':{
                    'c1':0,
                    'c2':0,
                    'c3':0,
                },
                'output':{
                    'a1':0,
                    'a2':0,
                    'a3':0,
                },
            },
            'up3':{
                'intake':{
                    'c1':0,
                    'c2':0,
                    'c3':0,
                },
                'output':{
                    'a1':0,
                    'a2':0,
                    'a3':0,
                },
            },
        },
        'f2':{
            'up0':{
                'intake':{
                    'c1':0,
                    'c2':0,
                    'c3':0,
                },
                'output':{
                    'a1':0,
                    'a2':0,
                    'a3':0,
                },
            },
            'up1':{
                'intake':{
                    'c1':0,
                    'c2':0,
                    'c3':0,
                },
                'output':{
                    'a1':0,
                    'a2':0,
                    'a3':0,
                },
            },
            'up2':{
                'intake':{
                    'c1':0,
                    'c2':0,
                    'c3':0,
                },
                'output':{
                    'a1':0,
                    'a2':0,
                    'a3':0,
                },
            },
            'up3':{
                'intake':{
                    'c1':0,
                    'c2':0,
                    'c3':0,
                },
                'output':{
                    'a1':0,
                    'a2':0,
                    'a3':0,
                },
            },
        },
        'f3':{
            'up0':{
                'intake':{
                    'c1':0,
                    'c2':0,
                    'c3':0,
                },
                'output':{
                    'a1':0,
                    'a2':0,
                    'a3':0,
                },
            },
            'up1':{
                'intake':{
                    'c1':0,
                    'c2':0,
                    'c3':0,
                },
                'output':{
                    'a1':0,
                    'a2':0,
                    'a3':0,
                },
            },
            'up2':{
                'intake':{
                    'c1':0,
                    'c2':0,
                    'c3':0,
                },
                'output':{
                    'a1':0,
                    'a2':0,
                    'a3':0,
                },
            },
            'up3':{
                'intake':{
                    'c1':0,
                    'c2':0,
                    'c3':0,
                },
                'output':{
                    'a1':0,
                    'a2':0,
                    'a3':0,
                },
            },
        },
    },
}
'''
FDICT = {}
def loadjson():
    global FDICT
    import json
    from .models import Post
    p = Post.objects.filter(title='factoryjson')
    p = p[0].content
    print('=================')
    FDCT = json.loads(p)
    print(FDCT)
    for key,d in FDCT.items():
        print(type(key),key)
        FDICT[int(key)] = d
def loadjsonwrapper():
    global FDICT
    loadjson()
loadjsonwrapper()
#app_json = json.dumps(FDICT,indent=4)
#print(app_json)